### ISSUE TITLE
Test Recording files getting deleted after recording tests for ContainerInstance module

### ISSUE THREAD

**Issue by diyellap** [Azure/autorest.powershell#1111] opened 2023-02-10 04:15 UTC
### Description

Hi,

For ContainerInstance module, I created my branch on top of 'generation' branch, generated code from new swagger, added new tests and ran all tests with the command: **pwsh test-module.ps1 -record**. All tests ran fine but all previous recording files under test/ folder were deleted, and no new recording files were added. Can you please let me know how to resolve this issue?

        deleted:    Add-AzContainerInstanceOutput.Recording.json
        deleted:    Get-AzContainerGroup.Recording.json
        deleted:    Get-AzContainerInstanceCachedImage.Recording.json
        deleted:    Get-AzContainerInstanceCapability.Recording.json
        deleted:    Get-AzContainerInstanceLog.Recording.json
        deleted:    Get-AzContainerInstanceUsage.Recording.json
        deleted:    Invoke-AzContainerInstanceCommand.Recording.json
        deleted:    New-AzContainerGroup.Recording.json
        deleted:    Remove-AzContainerGroup.Recording.json
        deleted:    Restart-AzContainerGroup.Recording.json
        deleted:    Start-AzContainerGroup.Recording.json
        deleted:    Stop-AzContainerGroup.Recording.json
        deleted:    Update-AzContainerGroup.Recording.json

**Comment by isra-fel** [comment] 2023-02-10 06:03
Hi @diyellap can you push your updates and share your branch?

**Comment by diyellap** [comment] 2023-02-10 21:59
Yes, all tests ran fine but no recording file was generated:
**Tests completed in 1284.34s
Tests Passed: 58, Failed: 0, Skipped: 7,**

Here's my branch: https://github.com/diyellap/azure-powershell/tree/spot-confidential-containers . I pushed my updates here along with the newly added test files. It was generated on top of generation branch not main branch.

**Comment by diyellap** [comment] 2023-02-10 22:02
***@***.******@***.***> @***@***.***> @FNU ***@***.***>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by dolauli** [comment] 2023-02-28 05:37
Closed it since the issue can not be reproduced after the developer created a new branch from the generation branch.

**Closed by dolauli** 2023-02-28 05:37 UTC
Labels: bug
