### ISSUE TITLE
Make a parameter mandatory / not mandatory

### ISSUE THREAD

**Issue by dicolanl** [Azure/autorest.powershell#862] opened 2021-11-14 20:28 UTC
Is there a directive to be able to make a parameter mandatory or not?  

Api spec has a property of a model as mandatory, but when the cmdlet is autogenerated it is not listed as mandatory?

**Comment by dolauli** [comment] 2021-11-15 02:11
Close it since the issue is a duplicated issue as https://github.com/Azure/autorest.powershell/issues/799.

**Closed by dolauli** 2021-11-15 02:11 UTC
