### ISSUE TITLE
[Error/Warning/Information]Variable having duplicate information

### ISSUE THREAD

**Issue by Man2MSFT** [Azure/autorest.powershell#929] opened 2022-04-01 04:05 UTC
As you can see here in attached image, if we use common variables like ErrorVariable, WarningVariable etc with the cmdlet which is present in ProxyCmdletDefinition file, then it is logging information more than once.

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/102780775/161192652-69946220-82c3-43f6-8b11-edd1319d7629.png)

if we remove ErrorVariable at ProxyCmdletDefinition - then its content come same as $error variable, like given below-

`if ($PSBoundParameters.ContainsKey('ErrorVariable')) {
    $null = $PSBoundParameters.Remove('ErrorVariable')
}`

please check and try to fix it. Thank you!!

**Comment by dolauli** [comment] 2022-04-06 02:08
It seems the issue has nothing to do with whether $Errorvariable is passed through. And the issue happens only when **$ErrorActionPreference** is set to **stop**. Will need to talk to PowerShell team for the expected behavior.
![image](https://user-images.githubusercontent.com/11451757/161881414-10ebcd0e-097b-49f6-b879-6a3bf01d658e.png)
![image](https://user-images.githubusercontent.com/11451757/161881495-0481736c-d753-4dea-ba90-0fa0cd32c7fa.png)

**Comment by dolauli** [comment] 2022-04-11 02:16
It is a PowerShell issue, and we create an [issue ](https://github.com/PowerShell/PowerShell/issues/17123#issuecomment-1092634424)in PowerShell repo.

**Comment by dolauli** [comment] 2022-06-09 03:09
Closed it since it is a powershell issue.

**Closed by dolauli** 2022-06-09 03:09 UTC
Labels: investigate
