### ISSUE TITLE
Wrong service url construction for open api paths with date parameters

### ISSUE THREAD

**Issue by timayabi2020** [Azure/autorest.powershell#1025] opened 2022-11-14 20:44 UTC
The API implementation class constructs a wrong service url for services with date parameters.
The date parameter is being appended as a logical operator (date==<value>) instead of an assignment operator (date=<value>). See below
<img width="880" alt="image" src="https://user-images.githubusercontent.com/10947120/201759817-74c097b7-f854-402b-a1b2-bd5718a11af2.png">

The affected powershell commands will be failing with the following message
<img width="661" alt="image" src="https://user-images.githubusercontent.com/10947120/201760078-c9153e65-58e8-4b78-8a35-bf562c955e46.png">

The service owner has described the usage of parameters as assignment operators on such paths. See below
<img width="437" alt="image" src="https://user-images.githubusercontent.com/10947120/201760788-9d0f3f6a-cc01-4b4a-9b95-fe3dd11f74c8.png">

The Url is supposed to be constructed as such
<img width="565" alt="image" src="https://user-images.githubusercontent.com/10947120/201761132-2f7ee0c4-1640-4629-bda3-5e09a80cd097.png">

and a successful command execution will be as below image
<img width="983" alt="image" src="https://user-images.githubusercontent.com/10947120/201761586-492f7109-c619-45ff-a38b-0be28d99c5fe.png">

**Comment by peombwa** [comment] 2023-05-18 15:56
@dolauli, any updates on when the issue will be fixed? Customers are still facing the issue when using commands that accept date parameters. Is there a workaround you'd suggest?

**Comment by dolauli** [comment] 2023-05-19 06:29
> @dolauli, any updates on when the issue will be fixed? Customers are still facing the issue when using commands that accept date parameters. Is there a workaround you'd suggest?

I do not plan to fix in v3, since it seems not a common case that an API is designed like this.
The workaround should be easy, you may change the generated code with a directive as below.
```
- from: sourcename.cs
  where: $
  transform: $ = $.replace('old code', 'new code')
```

**Comment by peombwa** [comment] 2023-05-22 16:09
Thanks for the suggestion! We went with a similar approach by using `from: source-file-csharp` directive. Will be issue be addressed in v4?

**Comment by BethanyZhou** [comment] 2023-06-02 06:16
Hi @peombwa , could you kindly provide minimal codes to help me reproduce this issue. I'm going to look into this issue

**Closed** 2023-06-08 08:06 UTC
Labels: bug, v4
